// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nChoosek
int nChoosek(int n, int k);
RcppExport SEXP _rGUIDANCE_nChoosek(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(nChoosek(n, k));
    return rcpp_result_gen;
END_RCPP
}
// msa_recode
List msa_recode(NumericMatrix msa);
RcppExport SEXP _rGUIDANCE_msa_recode(SEXP msaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type msa(msaSEXP);
    rcpp_result_gen = Rcpp::wrap(msa_recode(msa));
    return rcpp_result_gen;
END_RCPP
}
// res_pair_hit
NumericMatrix res_pair_hit(NumericMatrix col2res);
RcppExport SEXP _rGUIDANCE_res_pair_hit(SEXP col2resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type col2res(col2resSEXP);
    rcpp_result_gen = Rcpp::wrap(res_pair_hit(col2res));
    return rcpp_result_gen;
END_RCPP
}
// add_msa
IntegerMatrix add_msa(IntegerMatrix ref_col2res, IntegerMatrix alt_col2res, IntegerMatrix alt_res2col, IntegerMatrix hit_mat);
RcppExport SEXP _rGUIDANCE_add_msa(SEXP ref_col2resSEXP, SEXP alt_col2resSEXP, SEXP alt_res2colSEXP, SEXP hit_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ref_col2res(ref_col2resSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type alt_col2res(alt_col2resSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type alt_res2col(alt_res2colSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type hit_mat(hit_matSEXP);
    rcpp_result_gen = Rcpp::wrap(add_msa(ref_col2res, alt_col2res, alt_res2col, hit_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rGUIDANCE_nChoosek", (DL_FUNC) &_rGUIDANCE_nChoosek, 2},
    {"_rGUIDANCE_msa_recode", (DL_FUNC) &_rGUIDANCE_msa_recode, 1},
    {"_rGUIDANCE_res_pair_hit", (DL_FUNC) &_rGUIDANCE_res_pair_hit, 1},
    {"_rGUIDANCE_add_msa", (DL_FUNC) &_rGUIDANCE_add_msa, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rGUIDANCE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
